<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
    <AvaloniaXaml Remove="App.axaml" />
    <AvaloniaResource Include="App.axaml" />
    <Folder Include="Analytics\Interfaces\Repozitories\" />
    <Folder Include="Analytics\Services\Repozitories\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.0.2" />
    <PackageReference Include="Avalonia.Desktop" Version="12.0.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.2" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.2" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.1">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.1" />
    <PackageReference Include="DialogHost.Avalonia" Version="0.12.2" />
    <PackageReference Include="LiveChartsCore" Version="2.0.4" />
    <PackageReference Include="MessageBox.Avalonia" Version="12.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.8" />
    <PackageReference Include="System.Net.Http.Json" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="CRM\Views\Elements\CreateApplicationView.axaml.cs">
      <DependentUpon>CreateApplicationView.axaml</DependentUpon>
    </Compile>
    <Compile Update="CRM\Views\Elements\Deals\DealInListView.axaml.cs">
      <DependentUpon>DealInListView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Shared\Views\Elements\HeaderView.axaml.cs">
      <DependentUpon>HeaderView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Shared\Views\Elements\SidebarView.axaml.cs">
      <DependentUpon>SidebarView.axaml</DependentUpon>
    </Compile>
    <Compile Update="CRM\Views\Pages\DealPageView.axaml.cs">
      <DependentUpon>DealPageView.axaml</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
