<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
    <AvaloniaXaml Remove="CRM\Views\Elements\Deals\**" />
    <AvaloniaXaml Remove="Shared\Interfaces\Repozitories\**" />
    <Compile Remove="CRM\Views\Elements\Deals\**" />
    <Compile Remove="Shared\Interfaces\Repozitories\**" />
    <EmbeddedResource Remove="CRM\Views\Elements\Deals\**" />
    <EmbeddedResource Remove="Shared\Interfaces\Repozitories\**" />
    <None Remove="CRM\Views\Elements\Deals\**" />
    <None Remove="Shared\Interfaces\Repozitories\**" />
    <Compile Remove="CRM\Views\Elements\Deals\**" />
    <EmbeddedResource Remove="CRM\Views\Elements\Deals\**" />
    <Folder Include="Shared\Interfaces\Repozitories\" />
    <None Remove="CRM\Views\Elements\Deals\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.0.2" />
    <PackageReference Include="Avalonia.Desktop" Version="12.0.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.2" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.2" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.1">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.1" />
    <PackageReference Include="DialogHost.Avalonia" Version="0.12.2" />
    <PackageReference Include="MessageBox.Avalonia" Version="12.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.8" />
    <PackageReference Include="System.Net.Http.Json" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="CRM\Views\Elements\CreateApplicationView.axaml.cs">
      <DependentUpon>CreateApplicationView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Shared\Views\Elements\CreateEditUserView.axaml.cs">
      <DependentUpon>CreateEditUserView.axaml</DependentUpon>
    </Compile>
    <Compile Update="TaskManager\Views\Elements\AppointmentDealView.axaml.cs">
      <DependentUpon>AppointmentDealView.axaml</DependentUpon>
    </Compile>
    <Compile Update="TaskManager\Views\Elements\CreateEditTaskView.axaml.cs">
      <DependentUpon>CreateEditTaskView.axaml</DependentUpon>
    </Compile>
    <Compile Update="TaskManager\Views\Elements\DealInListView.axaml.cs">
      <DependentUpon>DealInListView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Shared\Views\Elements\HeaderView.axaml.cs">
      <DependentUpon>HeaderView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Shared\Views\Elements\SidebarView.axaml.cs">
      <DependentUpon>SidebarView.axaml</DependentUpon>
    </Compile>
    <Compile Update="TaskManager\Views\Pages\DeadlineDashboardPageView.axaml.cs">
      <DependentUpon>DeadlineDashboardPageView.axaml</DependentUpon>
    </Compile>
    <Compile Update="TaskManager\Views\Pages\DealPageView.axaml.cs">
      <DependentUpon>DealPageView.axaml</DependentUpon>
    </Compile>
    <Compile Update="TaskManager\Views\PopUp\AssignDealView.axaml.cs">
      <DependentUpon>AssignDealView.axaml</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
